--Part – A 
--1.	INSERT Procedures: Create stored procedures to insert records into STUDENT tables (SP_INSERT_STUDENT)
CREATE OR ALTER PROCEDURE PR_INSERT_STUDENT
@STUID INT,
@NAME VARCHAR(100),
@EMAIL VARCHAR(100),
@PHONE VARCHAR(15),
@DEPARTMENT VARCHAR(50),
@DOB DATE,
@ENROLLMENTYEAR INT

AS 
BEGIN 
INSERT INTO STUDENT (STUDENTID,STUNAME,STUEMAIL,STUPHONE,STUDEPARTMENT,STUDATEOFBIRTH,STUENROLLMENTYEAR ) 
VALUES (@STUID,@NAME ,@EMAIL,@PHONE,@DEPARTMENT,@DOB ,@ENROLLMENTYEAR)
INSERT INTO STUDENT (STUDENTID,STUNAME,STUEMAIL,STUPHONE,STUDEPARTMENT,STUDATEOFBIRTH,STUENROLLMENTYEAR ) 
VALUES (@STUID,@NAME ,@EMAIL,@PHONE,@DEPARTMENT,@DOB ,@ENROLLMENTYEAR)
END
EXEC PR_INSERT_STUDENT 10,	'Harsh Parmar',	'harsh@univ.edu',	'9876543218',	'CSE',	'2005-09-18',	2023;
EXEC PR_INSERT_STUDENT 20, 'Om Patel','om@univ.edu','9876543211','IT','2022-08-22',2022;
SELECT * FROM STUDENT

--2.	INSERT Procedures: Create stored procedures to insert records into COURSE tables 
--(SP_INSERT_COURSE)


CREATE OR ALTER PROCEDURE PR_INSERT_COURSE
@CID VARCHAR(10),
@CNAME VARCHAR(100),
@CCREDITS INT,
@CDEPT VARCHAR(50),
@CSEM INT
AS
BEGIN
	INSERT INTO COURSE(COURSEID,COURSENAME,COURSECREDITS,COURSEDEPARTMENT,COURSESEMESTER)
	VALUES(@CID,@CNAME,@CCREDITS,@CDEPT,@CSEM)
	INSERT INTO COURSE(COURSEID,COURSENAME,COURSECREDITS,COURSEDEPARTMENT,COURSESEMESTER)
	VALUES(@CID,@CNAME,@CCREDITS,@CDEPT,@CSEM)
END
EXEC PR_INSERT_COURSE 'CS330','Computer Networks',4,'CSE',5
EXEC PR_INSERT_COURSE 'EX120','Electronics Circuits',3,'ECE',2

SELECT * FROM COURSE
--3.	UPDATE Procedures: Create stored procedure SP_UPDATE_STUDENT to update Email and Phone in STUDENT table. (Update using studentID)
		CREATE OR ALTER PROCEDURE PR_UPDATE_STUDENT
		@STUID INT,
		@EMAIL VARCHAR(100),
		@PHONE VARCHAR(15)
		AS 
		BEGIN
			UPDATE STUDENT
			SET STUEMAIL = @EMAIL,STUPHONE = @PHONE
			WHERE STUDENTID = @STUID
		END
		EXEC PR_UPDATE_STUDENT 10,'harsh#univ.edu','123456789'
		SELECT * FROM STUDENT
_--4.	DELETE Procedures: Create stored procedure SP_DELETE_STUDENT to delete records from STUDENT where Student Name is Om Patel.
		CREATE OR ALTER PROCEDURE PR_DELETE_STUDENT
		@NAME VARCHAR(100)
		AS
		BEGIN
			DELETE 
			FROM STUDENT
			WHERE STUNAME = @NAME
		END
		EXEC PR_DELETE_STUDENT 'Om Patel'
		SELECT * FROM STUDENT
--5.	SELECT BY PRIMARY KEY: Create stored procedures to select records by primary key (SP_SELECT_STUDENT_BY_ID) from Student table.
		CREATE OR ALTER PROCEDURE PR_SELECT_STUDENT_BY_ID
		@ID INT
		AS
		BEGIN
			SELECT *
			FROM STUDENT
			WHERE STUDENTID = @ID
		END
		EXEC PR_SELECT_STUDENT_BY_ID 5
--6.	Create a stored procedure that shows details of the first 5 students ordered by EnrollmentYear.
		CREATE OR ALTER PROCEDURE PR_ORDER_BY_STUDENT

		AS
		BEGIN
			SELECT TOP 5 STUNAME
			FROM STUDENT
			ORDER BY STUENROLLMENTYEAR
		END

		EXEC PR_ORDER_BY_STUDENT
--Part – B  
--7.	Create a stored procedure which displays faculty designation-wise count.
		CREATE OR ALTER PROCEDURE PR_FACULTY_GROUP_BY
		AS
		BEGIN
			SELECT FACULTYDESIGNATION,COUNT(FACULTYNAME) AS COUNT_FACULTY
			FROM FACULTY
			GROUP BY FACULTYDESIGNATION
		END
		EXEC PR_FACULTY_GROUP_BY
--8.	Create a stored procedure that takes department name as input and returns all students in that department.
		CREATE OR ALTER PROCEDURE PR_DEPTARTMENT
		@SDEPT VARCHAR(50)
		AS
		BEGIN
			SELECT *
			FROM STUDENT 
			WHERE StuDepartment = @SDEPT
		END

		EXEC PR_DEPTARTMENT @SDEPT = 'CSE'

--Part – C 
--9.	Create a stored procedure which displays department-wise maximum, minimum, and average credits of courses.
		CREATE OR ALTER PROCEDURE PR_COURSE_MAX_MIN_AVG
		AS
		BEGIN
			SELECT CourseDepartment,MAX(CourseCredits) AS MAX_CREDITES,
									MIN(CourseCredits) AS MIN_VREDITES,
									AVG(CourseCredits) AS AVG_CREDITES
			FROM COURSE
			GROUP BY CourseDepartment
		END
		EXEC PR_COURSE_MAX_MIN_AVG
--10.	Create a stored procedure that accepts StudentID as parameter and returns all courses the student is enrolled in with their grades.
		CREATE OR ALTER PROCEDURE PR_JOINING_TABLE
		@STUID INT
		AS 
		BEGIN
			SELECT C.COURSENAME,E.GRADE
			FROM COURSE C
			JOIN ENROLLMENT E
			ON C.COURSEID = E.COURSEID
			WHERE E.STUDENTID = @STUID
		END

		EXEC PR_JOINING_TABLE 1

