--Table :
CREATE TABLE 
Log(LogMessage varchar(100), logDate Datetime)

SELECT * FROM LOG

--Part – A


--1.Create trigger for printing appropriate message after student registration.
CREATE OR ALTER TRIGGER TR_STUDENT_REGISTRATION
ON STUDENT
FOR INSERT
AS
BEGIN
	PRINT 'AFTER STUDENT REGISTRATION'
END

INSERT INTO STUDENT VALUES(15,'RAJ','RAG@GMAIL.COM',1254387,'CSE','2005-05-01',2021,7)

DROP TRIGGER TR_STUDENT_REGISTRATION 
--2.Create trigger for printing appropriate message after faculty deletion.
CREATE OR ALTER TRIGGER TR_FACULTY
ON FACULTY
AFTER DELETE
AS
BEGIN
	PRINT 'AFTER FACULTY DELETION'
END

DROP TRIGGER TR_FACULTY

DELETE 
FROM FACULTY
WHERE FACULTYID = 110
INSERT INTO FACULTY VALUES(1,'RAJKUMAR','RAG@GMAIL.COM','CSE','PROFFESERSE','2022-5-10')


SELECT * FROM FACULTY
--3.Create trigger for monitoring all events on course table. (print only appropriate message)
CREATE OR ALTER TRIGGER TR_MONITERING_COURSE
ON COURSE
AFTER INSERT,UPDATE,DELETE
AS
BEGIN 
	PRINT 'MONITERING ALL EVENTS'
END

DROP TRIGGER TR_MONITERING_COURSE

INSERT INTO COURSE VALUES('CSE1','SOFTWEAR ENGINEERING',2,'SE',5)

UPDATE COURSE
SET COURSEID = 'ME1'
WHERE COURSEID = 'CSE1'

DELETE 
FROM COURSE 
WHERE COURSEID = 'ME1'

SELECT * FROM COURSE
--4.Create trigger for logging data on new student registration in Log table.
	CREATE OR ALTER TRIGGER TR_NEW_STUDENT_REGISTRATION
	ON STUDENT
	AFTER INSERT
	AS
	BEGIN 
		DECLARE @SID INT
		SELECT @SID = StudentID FROM INSERTED
		INSERT INTO LOG VALUES ('RECORD WITH ID = '+CAST(@SID AS VARCHAR)+'INSERTED',GETDATE())
	END

	DROP TRIGGER TR_NEW_STUDENT_REGISTRATION

	INSERT INTO STUDENT VALUES(20,'PRIYAL','PRIYAL@EMAIL.COM','12458369','CSE','2005-02-01',2021,8)

	SELECT * FROM STUDENT
	SELECT * FROM LOG
--5.Create trigger for auto-uppercasing faculty names.
	CREATE OR ALTER TRIGGER TR_AUTO_UPPERCASING_FACULTY
	ON FACULTY
	AFTER INSERT
	AS
	BEGIN
		--DECLARE @FID INT,@FNAME VARCHAR(10)
		--SELECT @FID = FacultyID FROM INSERTED
		--SELECT @FNAME = FacultyName FROM INSERTED
	

	UPDATE f
	SET FacultyName = UPPER(f.FacultyName)
	from FACULTY f
	join inserted i
	ON f.FacultyID = i.FacultyID

	END

	INSERT INTO FACULTY VALUES(2,'Dhruvi','DHRUVI@GMAIL.COM','CE','PROFFESER','2005-05-01')
	DROP TRIGGER TR_AUTO_UPPERCASING_FACULTY
	SELECT * FROM FACULTY
	SELECT * FROM LOG
--6.Create trigger for calculating faculty experience (Note: Add required column in faculty table)
ALTER TABLE FACULTY
ADD Experience INT;

	CREATE OR ALTER TRIGGER TR_CALCULATING_FACULTY
	ON FACULTY 
	FOR INSERT,UPDATE
	AS
	BEGIN
		DECLARE @JD DATE
		SELECT @JD = FacultyJoiningDate FROM inserted
		UPDATE  F
		SET Experience = DATEDIFF(YEAR,@JD,GETDATE())
		FROM FACULTY F
		JOIN inserted I
		ON F.FacultyID = I.FACULTYID
	END
	DROP TRIGGER TR_CALCULATING_FACULTY
	INSERT INTO FACULTY VALUES(3,'Dhruvi','DHRUVI@GMAIL.COM','CE','PROFFESER','2005-05-01')
	SELECT * FROM FACULTY
	

--Part – B
--7.Create trigger for auto-stamping enrollment dates.
CREATE OR ALTER TRIGGER TR_AFTER_ENROLLMENT_AUTO_STAMPING_DATES
ON ENROLLMENT
AFTER INSERT 
AS 
BEGIN

	UPDATE e
	SET EnrollmentDate = GETDATE()
	FROM ENROLLMENT e
	JOIN inserted i
    ON e.EnrollmentID = i.EnrollmentID;
END
INSERT INTO ENROLLMENT VALUES(12,'CS101',NULL,'A+','Completed')

SELECT * FROM ENROLLMENT

DROP TRIGGER TR_AFTER_ENROLLMENT_AUTO_STAMPING_DATES

--8.Create trigger for logging data After course assignment - log course and faculty detail.
CREATE OR ALTER TRIGGER TR_AFTER_COURSE_ASSIGN_LOG
ON COURSE_ASSIGNMENT
AFTER INSERT
AS
BEGIN
	DECLARE @CID_8 INT,@FID_8 INT
    SELECT @CID_8=COURSEID,@FID_8=FACULTYID FROM INSERTED

	INSERT INTO LOG VALUES(
        'Course ' + CAST(@CID_8 AS VARCHAR) +
        ' assigned to Faculty ' + CAST(@FID_8 AS VARCHAR),
        GETDATE())    
END;

DROP TRIGGER TR_AFTER_COURSE_ASSIGN_LOG

--Part - C
--9.Create trigger for updating student phone and print the old and new phone number.
CREATE OR ALTER TRIGGER TR_AFTER_STUDENT_PHONE_UPDATE
ON STUDENT
AFTER UPDATE
AS
BEGIN
	DECLARE @OP VARCHAR(15),@NP VARCHAR(15)

    SELECT @NP=STUPHONE FROM INSERTED
	SELECT @OP=STUPHONE FROM DELETED

    PRINT 'OLD PHONE NUMBER:'+@OP
	PRINT 'NEW PHONE NUMBER:'+@NP

END;
SELECT * FROM STUDENT

UPDATE STUDENT
SET STUPHONE='4561237892'
WHERE STUDENTID=12

DROP TRIGGER TR_AFTER_STUDENT_PHONE_UPDATE

--10.Create trigger for updating course credit log old and new credits in log table.
CREATE OR ALTER TRIGGER TR_AFTER_COURSE_CREDIT_LOG
ON COURSE
AFTER UPDATE
AS
BEGIN
	DECLARE @OLD INT,@NEW INT
	SELECT @NEW=CourseCredits FROM INSERTED
	SELECT @OLD=CourseCredits FROM DELETED
    
	INSERT INTO LOG VALUES('OLD CREDITS:'+CAST(@OLD AS VARCHAR)+
	                        'NEW CREDITS:'+CAST(@NEW AS VARCHAR),GETDATE())
END;


UPDATE COURSE
SET CourseCredits=4
WHERE CourseID='ME101'

SELECT * FROM COURSE
SELECT * FROM LOG

DROP TRIGGER TR_AFTER_COURSE_CREDIT_LOG