--Table : 
CREATE TABLE LOG1(LogMessage varchar(100), logDate Datetime)
SELECT * FROM LOG1
--Part – A
--1.Create trigger for blocking student deletion.
CREATE OR ALTER TRIGGER TR_BLOCKING_STUDENT
ON STUDENT
INSTEAD OF DELETE
AS
BEGIN 
	PRINT('SOMEONE TRIED TO DELETE AN OPERATION IN THE STUDENT TABLE')
END

DROP TRIGGER TR_BLOCKING_STUDENT
DELETE
FROM STUDENT 
WHERE StuName = 'Priya Shah'
--2.Create trigger for making course read-only.
CREATE TRIGGER TR_MAKING_COURSE
ON COURSE
INSTEAD OF INSERT,UPDATE,DELETE
AS
BEGIN
	PRINT('SOMEONE TRIED TO INSERTE AN OPERATION IN THE COURSE TABLE')
END
DROP TRIGGER TR_MAKING_COURSE
INSERT INTO COURSE VALUES('CS101','SOFTWEAR ENGINNERING',3,'IT',1)

UPDATE COURSE
SET CourseCredits = 5
WHERE CourseCredits = 3

DELETE 
FROM COURSE
WHERE CourseName = 'Web Technologies'
--3.Create trigger for preventing faculty removal.
CREATE OR ALTER TRIGGER TR_FACULTY
ON FACULTY
INSTEAD OF DELETE
AS
BEGIN
	PRINT('SOMEONE TRIED TO DELETE AN OPERATION IN THE FACULTY TABLE')
END

DROP TRIGGER TR_FACULTY
DELETE
FROM FACULTY
WHERE FacultyName = 'Dr. Sheth'

--4.Create instead of trigger to log all operations on COURSE (INSERT/UPDATE/DELETE) into Log table. (Example: INSERT/UPDATE/DELETE operations are blocked for you in course table)
CREATE OR ALTER TRIGGER TR_ALLopRATION_LOG
ON COURSE
INSTEAD OF INSERT,UPDATE,DELETE
AS
BEGIN
	IF EXISTS(SELECT * FROM INSERTED) AND NOT EXISTS (SELECT * FROM DELETED) 
	BEGIN 
		INSERT INTO LOG1 VALUES('SOMEONE TRIED TO INSERTE AN OPERATION IN THE COURSE TABLE',GETDATE())
	END

	ELSE IF UPDATE(CourseName)
	BEGIN
		INSERT INTO LOG1 VALUES('SOMEONE TRIED TO UPDATE AN OPERATION IN THE COURSE TABLE',GETDATE())
	END

	ELSE IF EXISTS(SELECT * FROM DELETED) AND NOT EXISTS(SELECT * FROM INSERTED)
	BEGIN
		INSERT INTO LOG1 VALUES('SOMEONE TRIED TO DELETE AN OPERATION IN THE COURSE TABLE',GETDATE())
	END
END

DROP TRIGGER  TR_ALLopRATION_LOG
INSERT INTO COURSE VALUES('CS125','SOFTWEAR ENGINNERING',5,'IT',3)
SELECT * FROM COURSE
UPDATE COURSE
SET CourseName = 'BACKEND'
WHERE CourseName = 'Microprocessors'

SELECT * FROM LOG1

DELETE 
FROM COURSE
WHERE CourseName = 'Data Structures'


--5.Create trigger to Block student to update their enrollment year and print message ‘students are not allowed to update their enrollment year’
CREATE TRIGGER TR_STUDENT_ENYEAR
ON STUDENT
INSTEAD OF UPDATE
AS
BEGIN 
	IF UPDATE(StuEnrollmentYear)
		PRINT('students are not allowed to update their enrollment year')
END

DROP TRIGGER TR_STUDENT_ENYEAR

SELECT * FROM STUDENT
UPDATE STUDENT
SET StuEnrollmentYear = '2025'
WHERE StuEnrollmentYear = '2022'
--6.Create trigger for student age validation (Min 18).
CREATE OR ALTER TRIGGER TR_STUDENT_VALIDATION
ON STUDENT
INSTEAD OF INSERT
AS
BEGIN
	
	DECLARE @AGE INT
	SELECT @AGE = DATEDIFF(YEAR,StuDateOfBirth,GETDATE()) FROM INSERTED
	IF(@AGE >= 18)
		INSERT INTO STUDENT(StudentID,StuName,StuEmail,StuPhone,StuDepartment,StuDateOfBirth,StuEnrollmentYear) 
		SELECT StudentID,StuName,StuEmail,StuPhone,StuDepartment,StuDateOfBirth,StuEnrollmentYear
		FROM INSERTED
END

DROP TRIGGER TR_STUDENT_VALIDATION
SELECT * FROM STUDENT

INSERT INTO STUDENT VALUES(150 , 'VISHVA' , 'CDJCJ' , '11546232654' , 'CSE' , '2003-03-03' , 2022 , 9)
--Part – B
--7.Create trigger for unique faculty’s email check.
CREATE OR ALTER TRIGGER TR_DUPLICATE_FACULTY
ON FACULTY
INSTEAD OF INSERT
AS
BEGIN
	IF EXISTS(SELECT 1
			FROM FACULTY F
			JOIN INSERTED I 
			ON F.FacultyEmail = I.FacultyEmail)
	BEGIN
		PRINT('ERROR:DUPLICATE NAME AN FACULTY WITH THIS NAME ALREADY EXITS')
		END
ELSE
	BEGIN
		INSERT INTO FACULTY(FacultyID,FacultyName,FacultyEmail,FacultyDepartment,FacultyDesignation,FacultyJoiningDate)
		SELECT FacultyID,FacultyName,FacultyEmail,FacultyDepartment,FacultyDesignation,FacultyJoiningDate FROM INSERTED
	END
END
DROP TRIGGER TR_DUPLICATE_FACULTY
INSERT INTO FACULTY VALUES(15,'DHRUVI','DHRUVI@GMAIL.COM','IT','PROFFESER','2007-7-15',NULL)
SELECT * FROM FACULTY
--8.Create trigger for preventing duplicate enrollment.
CREATE OR ALTER TRIGGER TR_DUPLICATE_ENROLLMENT



--Part - C
--9.Create trigger to Allow enrolment in month from Jan to August, otherwise print message enrolment closed.
CREATE OR ALTER TRIGGER TR_ENROOMENT_MESSAGE
ON ENROLLMENT
INSTEAD OF INSERT
AS
BEGIN
	DECLARE @EMONTH INT
	SELECT @EMONTH = MONTH(EnrollmentDate) FROM INSERTED
	IF(@EMONTH = 1 OR @EMONTH = 2 OR @EMONTH = 3 OR @EMONTH = 4 OR @EMONTH = 5 OR @EMONTH = 6 OR @EMONTH = 7 OR @EMONTH = 8)
	BEGIN
		INSERT INTO ENROLLMENT(STUDENTID,COURSEID,ENROLLMENTDATE,GRADE,ENROLLMENTSTATUS)
		SELECT STUDENTID,COURSEID,ENROLLMENTDATE,GRADE,ENROLLMENTSTATUS FROM INSERTED
	END
ELSE
		BEGIN
		PRINT('ERROR:DUPLICATE NAME AN FACULTY WITH THIS NAME ALREADY EXITS')
		END
END
DROP TRIGGER TR_ENROOMENT_MESSAGE
--10.Create trigger to Allow only grade change in enrollment (block other updates)
CREATE OR ALTER TRIGGER TR_ALLOW_GRADE
ON ENROLLMENT
AS
BEGIN 
	
	UPDATE ENROLLMENT
	SET GRADE
